# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
